#!/usr/bin/env bash

if [ ! -f ../../package.json ]; then
  echo "postinstall: ../../package.json not found; skipping @electron/rebuild (standalone clone)" >&2
  exit 0
fi

electron_version=$(node -p "require('../../package.json').optionalDependencies.electron.replace('^','')")

npx @electron/rebuild -v "$electron_version"
